
let savedEmail = "";
let savedPassword = "";

function showRegister() {
    document.getElementById('loginForm').classList.remove('active');
    document.getElementById('registerForm').classList.add('active');
}

function showLogin() {
    document.getElementById('registerForm').classList.remove('active');
    document.getElementById('loginForm').classList.add('active');
}

function createAccount() {
    const email = document.getElementById('newEmail').value;
    const password = document.getElementById('newPassword').value;

    if (email && password) {
        savedEmail = email;
        savedPassword = password;
        alert("Votre compte a été créé avec succès !");
        showLogin();
    } else {
        alert("Veuillez remplir tous les champs.");
    }
}

function login() {
    const email = document.getElementById('loginEmail').value;
    const password = document.getElementById('loginPassword').value;

    if (email === savedEmail && password === savedPassword) {
        alert("Connexion réussie !");
        window.location.href = "index.html";
    } else {
        alert("Email ou mot de passe incorrect.");
    }
}

const proverbs = [
    "À beau mentir qui vient de loin.",
    "À bon chat, bon rat.",
    "À chaque jour suffit sa peine.",
    "À cheval donné, on ne regarde pas les dents.",
    "À l'impossible nul n'est tenu.",
    "À malin, malin et demi.",
    "À quelque chose malheur est bon.",
    "Abondance de biens ne nuit pas.",
    "Après la pluie, le beau temps.",
    "Autant en emporte le vent.",
    "Aux grands maux, les grands remèdes.",
    "Bien mal acquis ne profite jamais.",
    "Ce qui est différé n’est pas perdu.",
    "Ce qui est fait n’est plus à faire.",
    "Chacun voit midi à sa porte.",
    "Charité bien ordonnée commence par soi-même.",
    "Chat échaudé craint l’eau froide.",
    "Comme on fait son lit, on se couche.",
    "Dis-moi qui tu hantes, je te dirai qui tu es.",
    "Donner c’est donner, reprendre c’est voler.",
    "Il faut battre le fer pendant qu’il est chaud.",
    "Il faut laver son linge sale en famille.",
    "Il n’est pire aveugle que celui qui ne veut pas voir.",
    "Il ne faut pas mettre la charrue avant les bœufs.",
    "Il ne faut pas vendre la peau de l’ours avant de l’avoir tué.",
    "L’arbre qui tombe fait plus de bruit que la forêt qui pousse.",
    "L’occasion fait le larron.",
    "La fortune sourit aux audacieux.",
    "La nuit porte conseil.",
    "La parole est d’argent, le silence est d’or.",
    "La patience est une vertu.",
    "Le mieux est l’ennemi du bien.",
    "Les absents ont toujours tort.",
    "Les apparences sont parfois trompeuses.",
    "Les cordonniers sont les plus mal chaussés.",
    "Les goûts et les couleurs ne se discutent pas.",
    "Mieux vaut être seul que mal accompagné.",
    "Mieux vaut prévenir que guérir.",
    "Nécessité fait loi.",
    "On apprend à tout âge.",
    "On ne change pas une équipe qui gagne.",
    "On ne fait pas d’omelette sans casser des œufs.",
    "On n’est jamais mieux servi que par soi-même.",
    "Paris ne s’est pas fait en un jour.",
    "Petit à petit, l’oiseau fait son nid.",
    "Pierre qui roule n’amasse pas mousse.",
    "Plus on est de fous, plus on rit.",
    "Quand le chat n’est pas là, les souris dansent.",
    "Quand on veut, on peut.",
    "Rien ne sert de courir, il faut partir à point.",
    "Tel est pris qui croyait prendre.",
    "Trop de cuisiniers gâtent la sauce.",
    "Un tiens vaut mieux que deux tu l’auras.",
    "Un homme averti en vaut deux.",
    "Un malheur ne vient jamais seul.",
    "Vaut mieux tard que jamais.",
    "Vouloir, c’est pouvoir.",
    "À bon entendeur, salut.",
    "Chose promise, chose due.",
    "Il n'y a pas de fumée sans feu.",
    "Les murs ont des oreilles.",
    "Qui aime bien châtie bien.",
    "À cœur vaillant rien d'impossible.",
    "À l'œuvre on connaît l'artisan.",
    "L'argent ne fait pas le bonheur.",
    "Il faut tourner sept fois sa langue dans sa bouche avant de parler.",
    "La bave du crapaud n’atteint pas la blanche colombe.",
    "La curiosité est un vilain défaut.",
    "La faim justifie les moyens.",
    "La montagne a accouché d’une souris.",
    "Le chat parti, les souris dansent.",
    "Le ridicule ne tue pas.",
    "Les bons comptes font les bons amis.",
    "Les chiens aboient, la caravane passe.",
    "Les grands esprits se rencontrent.",
    "Mieux vaut un tiens que deux tu l’auras.",
    "On ne peut pas être au four et au moulin.",
    "Quand on parle du loup, on en voit la queue.",
    "Qui ne tente rien n’a rien.",
    "Qui sème le vent récolte la tempête.",
    "Qui trop embrasse mal étreint.",
    "Qui va à la chasse perd sa place.",
    "Reculer pour mieux sauter.",
    "Rira bien qui rira le dernier.",
    "Tel père, tel fils.",
    "Tirer les vers du nez.",
    "Tomber dans les pommes.",
    "Trop bon, trop con.",
    "Ventre affamé n’a pas d’oreilles.",
    "Vivre d’amour et d’eau fraîche.",
    "Vouloir le beurre et l’argent du beurre.",
    "À chaque oiseau son nid est beau.",
    "À trop parler on se perd.",
    "Appeler un chat un chat.",
    "Autre temps, autres mœurs.",
    "Bon sang ne saurait mentir.",
    "Chien qui aboie ne mord pas.",
    "C’est en forgeant qu’on devient forgeron.",
    "C’est la goutte d’eau qui fait déborder le vase.",
    "C’est la loi du plus fort.",
    "C’est le ton qui fait la chanson.",
    "Ce n’est pas la mer à boire.",
    "Ce qui ne nous tue pas nous rend plus forts.",
    "Celui qui cherche trouve.",
    "Chercher midi à quatorze heures.",
    "Contentement passe richesse.",
    "De deux maux, il faut choisir le moindre.",
    "Des goûts et des couleurs, on ne discute pas.",
    "Donner sa langue au chat.",
    "En avril, ne te découvre pas d’un fil.",
    "Il n’y a pas de rose sans épines.",
    "Il ne faut pas courir deux lièvres à la fois.",
    "Il pleut des cordes.",
    "Il y a anguille sous roche.",
    "Jamais deux sans trois.",
    "Jeu de main, jeu de vilain.",
    "L'amour rend aveugle.",
    "La fin justifie les moyens.",
    "La roue tourne.",
    "La vie est un long fleuve tranquille.",
    "Le monde appartient à ceux qui se lèvent tôt.",
    "Le silence est la meilleure réponse.",
    "Les voyages forment la jeunesse.",
    "Mieux vaut faire envie que pitié.",
    "Nul n’est prophète en son pays.",
    "On ne fait pas d’omelette sans casser d’œufs.",
    "On récolte ce que l’on sème.",
    "Patience et longueur de temps font plus que force ni que rage.",
    "Quand on n’a pas ce que l’on aime, il faut aimer ce que l’on a.",
    "Qui dort dîne.",
    "Qui n’avance pas recule.",
    "Qui ne dit mot consent.",
    "Qui peut le plus peut le moins.",
    "Rome ne s’est pas faite en un jour.",
    "Tant va la cruche à l’eau qu’à la fin elle se casse.",
    "Tout vient à point à qui sait attendre.",
    "Tous les chemins mènent à Rome.",
    "Travailler dur porte ses fruits.",
    "Une fois n’est pas coutume.",
    "Une hirondelle ne fait pas le printemps.",
    "Un clou chasse l’autre.",
    "Un esprit sain dans un corps sain.",
    "Un homme averti en vaut deux.",
    "Un mal pour un bien.",
    "Un tiens vaut mieux que deux tu l’auras.",
    "Valeur n’attend point le nombre des années.",
    "Vieille amitié ne craint pas la rouille.",
    "Vin vieux en bouteille neuve.",
    "Vouloir, c’est pouvoir.",
    "Il n’y a pas de rose sans épines.",
    "On ne fait pas d’omelette sans casser des œufs.",
    "Un tien vaut mieux que deux tu l’auras.",
    "Chasser le naturel, il revient au galop.",
    "Les cordonniers sont les plus mal chaussés.",
    "Quand le chat n’est pas là, les souris dansent.",
    "Il n’est pire aveugle que celui qui ne veut pas voir.",
    "Il faut tourner sept fois sa langue dans sa bouche avant de parler.",
    "À force de crier au loup, on ne vous croit plus.",
    "Nul n’est prophète en son pays.",
    "Bien mal acquis ne profite jamais.",
    "Qui veut voyager loin ménage sa monture.",
    "Tout ce qui brille n’est pas or.",
    "Le temps, c’est de l’argent.",
    "La roue tourne.",
    "L’amour est aveugle.",
    "Qui ne tente rien n’a rien.",
    "Il n’y a pas de fumée sans feu.",
    "Mieux vaut prévenir que guérir.",
    "L’union fait la force.",
    "Rira bien qui rira le dernier.",
    "Petit à petit, l’oiseau fait son nid.",
    "Les grands esprits se rencontrent.",
    "Il faut battre le fer tant qu’il est chaud.",
    "On récolte ce qu’on sème.",
    " L'habit ne fait pas le moine.",
    " Qui vivra verra.",
    " Mieux vaut tard que jamais.",
    " Tel est pris qui croyait prendre.",
    " Il ne faut pas vendre la peau de l’ours avant de l’avoir tué.",
    " Petit à petit, l’oiseau fait son nid.",
    " Chose promise, chose due.",
    " L’union fait la force.",
    " À bon chat, bon rat.",
    " Il n’y a pas de fumée sans feu.",
    " Les absents ont toujours tort.",
    " Qui ne tente rien n’a rien.",
    " À cheval donné, on ne regarde pas les dents.",
    "14. À l’impossible nul n’est tenu.",
    " Bien mal acquis ne profite jamais.",
    " Ce qui est différé n’est pas perdu.",
    " Il ne faut pas mettre la charrue avant les bœufs.",
    " Il faut battre le fer pendant qu’il est chaud.",
    " L’argent ne fait pas le bonheur.",
    " La curiosité est un vilain défaut.",
    " La nuit porte conseil.",
    " Les bons comptes font les bons amis.",
    " Nul n’est prophète en son pays.",
    " On ne fait pas d’omelette sans casser des œufs.",
    " Paris ne s’est pas fait en un jour.",
    " Qui aime bien châtie bien.",
    " Qui court deux lièvres à la fois n’en prend aucun.",
    " Qui n’avance pas recule.",
    " Rira bien qui rira le dernier.",
    " Trop de cuisiniers gâtent la sauce.",
    " Un tiens vaut mieux que deux tu l’auras.",
    " Vouloir, c’est pouvoir.",
    " Il ne faut jamais dire jamais.",
    " Mieux vaut prévenir que guérir.",
    " L’erreur est humaine.",
    " Il faut tourner sept fois sa langue dans sa bouche avant de parler.",
    " Les chiens ne font pas des chats.",
    " Loin des yeux, loin du cœur.",
    " Il faut rendre à César ce qui est à César.",
    " Tout vient à point à qui sait attendre.",
    " Aide-toi, le ciel t’aidera.",
    " À cœur vaillant rien d’impossible.",
    " Abondance de biens ne nuit pas.",
    " Bon sang ne saurait mentir.",
    " Charbonnier est maître chez lui.",
    " Comparaison n’est pas raison.",
    " Dis-moi qui tu fréquentes, je te dirai qui tu es.",
    " Faute avouée est à moitié pardonnée.",
    " Heureux les simples d’esprit.",
    " Il est plus facile de détruire que de construire.",
    " L’occasion fait le larron.",
    " La patience est une vertu.",
    " Le mieux est l’ennemi du bien.",
    " Le silence est d’or.",
    " Les paroles s’envolent, les écrits restent.",
    " Mieux vaut être seul que mal accompagné.",
    " Nul n’est censé ignorer la loi.",
    " On récolte ce que l’on sème.",
    " Petit poisson deviendra grand.",
    " Quand on veut, on peut.",
    " Qui sème le vent récolte la tempête.",
    " Rien ne sert de courir, il faut partir à point.",
    " Un malheur ne vient jamais seul.",
    " Vaut mieux tard que jamais.",
    " La roue tourne.",
    " Il n’est pire aveugle que celui qui ne veut pas voir.",
    " Chacun voit midi à sa porte.",
    " Mieux vaut être pauvre et en bonne santé que riche et malade.",
    " Il faut savoir perdre pour mieux gagner.",
    " Quand le chat n’est pas là, les souris dansent.",
    " À chaque jour suffit sa peine.",
    " Il n’y a pas de petites économies.",
    " Les goûts et les couleurs ne se discutent pas.",
    " L’eau va toujours à la rivière.",
    " À bon entendeur, salut.",
    "Chacun pour soi et Dieu pour tous.",
    " C’est en forgeant qu’on devient forgeron.",
    " Donne un poisson à un homme, il mangera un jour ; apprends-lui à pêcher, il mangera toujours.",
    "L’amour est aveugle.",
    " La fin justifie les moyens.",
    " Il faut de tout pour faire un monde.",
    " L’herbe est toujours plus verte ailleurs.",
    " À trop tirer sur la corde, elle casse.",
    " Qui va lentement va sûrement.",
    " Les murs ont des oreilles.",
    " On ne prête qu’aux riches.",
    " À bon entendeur, demi-mot suffit.",
    " À quelque chose malheur est bon.",
    " Un clou chasse l’autre.",
    " Quand on parle du loup, on en voit la queue.",
    " Il faut savoir tourner la page.",
    " Ce qui ne tue pas rend plus fort.",
    " Il faut savoir saisir sa chance.",
    " La vérité sort de la bouche des enfants.",
    " Mieux vaut un petit chez soi qu’un grand chez les autres.",
    " N’attache pas ton chien avec des saucisses.",
    " N’ouvre pas la bouche si tu ne veux pas qu’on t’y mette un mot.",
    " Une main lave l’autre.",
    " Le monde appartient à ceux qui se lèvent tôt.",
    " Quand il pleut, il mouille.",
    " Qui trop embrasse mal étreint.",
    " L’argent appelle l’argent.",
    " La beauté est dans l’œil de celui qui regarde.",
    " À vieux pots, les meilleures soupes.",
    " Il n’y a pas de sot métier.",
    " Qui va piano va sano.",
    " Il vaut mieux prévenir que guérir.",
    " Ce n’est pas la mer à boire.",
    "Quand on aime, on ne compte pas.",
    " Il faut faire avec.",
    " L’amour ne se commande pas.",
    " Il faut savoir mettre de l’eau dans son vin.",
    " Ce n’est pas parce qu’on a rien à dire qu’il faut se taire.",
    " Une promesse est une dette.",
    " Le temps, c’est de l’argent.",
    " Le cœur a ses raisons que la raison ignore.",
    " Il ne faut pas réveiller le chat qui dort.",
    " Les voyages forment la jeunesse.",
    " Il faut savoir donner pour recevoir.",
    " Nul ne peut servir deux maîtres.",
    " On ne change pas une équipe qui gagne.",
    " L’exception confirme la règle.",
    " Il ne faut pas avoir les yeux plus gros que le ventre.",
    " Mieux vaut faire envie que pitié.",
    " Qui dort dîne.",
    " Les conseilleurs ne sont pas les payeurs.",
    " La gourmandise est un vilain défaut.",
    " Le ridicule ne tue pas.",
    " Il ne faut pas mettre tous ses œufs dans le même panier.",
    " Il faut appeler un chat un chat.",
    " L’homme propose, Dieu dispose.",
    " Le malheur des uns fait le bonheur des autres.",
    " Quand le vin est tiré, il faut le boire.",
    " Il faut mieux être seul que mal accompagné.",
    " On ne peut pas être au four et au moulin.",
    " On ne fait pas d’omelette sans casser des œufs.",
    " Mieux vaut la tête bien faite que bien pleine.",
    " La parole est d’argent, le silence est d’or.",
    " Les arbres ne montent pas jusqu’au ciel.",
    " Mieux vaut un mauvais arrangement qu’un bon procès.",
    " Un malheur partagé est un malheur allégé.",
    " L’ignorance est mère de tous les maux.",
    " On n’apprend pas aux vieux singes à faire la grimace.",
    " Chacun son métier, les vaches seront bien gardées.",
    " On n’attrape pas les mouches avec du vinaigre.",
    " La parole est libre, mais les conséquences sont lourdes.",
    " On ne peut pas plaire à tout le monde.",
    " Il n’y a pas de rose sans épines.",
    " Quand le sage montre la lune, l’idiot regarde le doigt.",
    " Les grandes douleurs sont muettes.",
    " Ce n’est pas en tournant autour du pot qu’on fait de la soupe.",
    " Tout flatteur vit aux dépens de celui qui l’écoute.",
    " Mieux vaut être prudent que désolé.",
    " Le vin entre, la vérité sort.",
    " Il faut bien que jeunesse se passe.",
    " La vengeance est un plat qui se mange froid.",
    " La critique est aisée, mais l’art est difficile.",
    " Qui n’a pas d’imagination n’a pas d’ailes.",
    " Une hirondelle ne fait pas le printemps.",
    " Les grands esprits se rencontrent.",
    " Il faut battre le fer pendant qu’il est chaud.",
    " Il n’y a que les imbéciles qui ne changent pas d’avis.",
    " Qui veut voyager loin ménage sa monture.",
    " À chaque oiseau son nid est beau.",
    " Qui paye ses dettes s’enrichit.",
    " L’avenir appartient à ceux qui croient à la beauté de leurs rêves.",
    " Ce n’est pas la taille qui fait la force.",
    " À l’impossible nul n’est tenu.",
    " On ne jette pas la pierre quand on est dans une maison de verre.",
    " Qui rira vendredi, dimanche pleurera.",
    " À bon vin point d’enseigne.",
    " Il vaut mieux avoir des remords que des regrets.",
    " Il ne faut pas courir avant de savoir marcher.",
    " Tout excès nuit.",
    " Il n’est jamais trop tard pour bien faire.",
    " La valeur n’attend pas le nombre des années.",
    " C’est dans les vieux pots qu’on fait les meilleures soupes.",
    " L’habit fait le moine quand il est propre.",
    " La vérité blesse parfois.",
    " Qui aime bien, corrige bien.",
    " Il n’y a que la vérité qui fâche.",
    " Il faut savoir tendre l’autre joue.",
    " Il n’y a pas de secret pour celui qui veut savoir.",
    " Un homme averti en vaut deux.",
    " On récolte ce que l’on sème.",
    " Mieux vaut mourir debout que vivre à genoux.",
    " Une fois n’est pas coutume.",
    " À malin, malin et demi.",
    " Un homme sans parole est un homme sans honneur.",
    " Trop de paroles, peu d’actes.",
    " Qui a bu boira.",
    " La peur n’évite pas le danger.",
    " Ce n’est pas en changeant de collier qu’on devient un autre chien.",
    " Les poissons ne se vantent pas de nager.",
    " Celui qui ne fait rien ne se trompe jamais.",
    " Il faut être deux pour danser le tango.",
    " Il n’y a pas d’amour sans jalousie.",
    " La chance sourit aux audacieux.",
    " Il faut savoir lire entre les lignes.",
    " C’est l’intention qui compte."



];

const list = document.getElementById("proverb-list");
const search = document.getElementById("search");


function displayProverbs(filteredProverbs) {
    list.innerHTML = "";
    filteredProverbs.forEach((prov) => {
        const li = document.createElement("li");
        li.textContent = prov;
        list.appendChild(li);
    });
}


search.addEventListener("input", () => {
    const value = search.value.toLowerCase();
    const filtered = proverbs.filter((prov) =>
        prov.toLowerCase().includes(value)
    );
    displayProverbs(filtered);
});
displayProverbs(proverbs);



